### PR TITLE
[SYCL][Graph] Fix memory leak multithreading Finalize test

### PR DESCRIPTION
**Pull request by mfrancepillois**
'queue::submit' function is not thread-safe.
Consequently, threads in Finalize test cannot safely submit their graph to the same queue (this generates sometimes memory leaks). 
This commit updates this test so that each thread submits its graph to a different queue.

### CODE REVIEW

**Review by EwanC — APPROVED** [review]
I can't see anything in the SYCL spec about `queue::submit` not being thread-safe, so ass

**Comment by mfrancepillois** [comment]
I looked at the coded, and the mutex of the queue seems to be not taken when submit function is invoked.

**Comment by Bensuo** [comment]
> I can't see anything in the SYCL spec about `queue::submit` not being thread-safe, so ass

Did this comment get cut off? The spec mentions that every function in the classes including `queue` should be thread safe, so perhaps we should be reporting this as an issue upstream if it's not implemented correctly. Unless we are doing something in `ext_oneapi_graph()` that is unsafe?

**Comment by EwanC** [comment]
> > I can't see anything in the SYCL spec about `queue::submit` not being thread-safe, so ass
> 
> Did this comment get cut off? The spec mentions that every function in the classes including `queue` should be thread safe, so perhaps we should be reporting this as an issue upstream if it's not implemented correctly. Unless we are doing something in `ext_oneapi_graph()` that is unsafe?

haha yup, at an comical moment too 🤦 
Yes,  I was confirming this was an existing implementation issue with DPC++ rather than something in the spec. If we think it's an issue we should report a bug.

**Comment by reble** [comment]
If it's an issue we might want to think about a reproducer that doesn't involve use of our extension.
As a conclusion can we leave the test as is? And opt it out temporarily, until the issue gets resolved.

**Comment by mfrancepillois** [comment]
Actually it seems that the observed memory leaks were caused by our implementation.
PR #299 addresses this issue.
I therefore close this PR.

**Pull request closed without merging**
